#!/usr/bin/ansible-playbook -ihosts.ini
---
- name: "Local"
  hosts: local
  become: true
  gather_facts: false

  roles:
    - role: roles/install-syncthing
      become: true
      tags: syncthing, install-syncthing
    - role: roles/systemd-syncthing
      become: true
      tags: syncthing
