---
googlecloudsdk_apt_key_url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
googlecloudsdk_apt_key_dest: "/usr/share/keyrings/cloud.google.gpg"
googlecloudsdk_apt_repository: "deb [signed-by={{ googlecloudsdk_apt_key_dest }}] https://packages.cloud.google.com/apt cloud-sdk main"
