[Sizes]
SplitterPos=200
WindowSize=@Size(1090 641)

[View]
BigIconSize=48
Mode=Detailed
ShowThumbnails=true
SmallIconSize=24
SortColumn=mtime
SortFolderFirst=true
SortOrder=descending
ThumbnailIconSize=128
