[General]
__userfile__=true
backlightIdleness=50
backlightIdlenessOnBatteryDischarging=true
disableIdlenessWhenFullscreen=false
enableBatteryWatcher=true
enableExtMonLidClosedActions=true
enableIdlenessBacklightWatcher=false
enableIdlenessWatcher=true
enableLidWatcher=true
hibernateKeyAction=1
idlenessACAction=4
idlenessACTime=@Variant(\0\0\0\xf\0\x12O\x80)
idlenessAction=-2
idlenessBatteryAction=4
idlenessBatteryTime=@Variant(\0\0\0\xf\0\t'\xc0)
idlenessTime=@Variant(\0\0\0\xf\0\0\xea`)
idlenessTimeSecs=600
lidClosedAcAction=5
lidClosedAction=5
lidClosedExtMonAcAction=-1
lidClosedExtMonAction=-1
powerKeyAction=4
powerLowAction=4
powerLowLevel=2
powerLowWarning=40
runCheckLevel=1
showIcon=true
suspendKeyAction=4
useThemeIcons=false
