[General]
__userfile__=true
iconTheme=

[desktopswitch2]
alignment=Left
labelType=1
rows=2
showOnlyActive=true
type=desktopswitch

[kbindicator]
alignment=Right
keeper_type=application
layout_flag_pattern=
show_caps_lock=false
show_layout=true
show_num_lock=false
show_scroll_lock=false
type=kbindicator

[mainmenu]
alignment=Left
type=mainmenu

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
hide-on-overlap=false
iconSize=22
lineCount=1
lockPanel=false
opacity=100
panelSize=32
plugins=mainmenu, desktopswitch2, quicklaunch, taskbar, kbindicator, sysstat, volume, tray, statusnotifier, worldclock
position=Bottom
reserve-space=true
show-delay=0
visible-margin=true
width=100
width-percent=true

[quicklaunch]
alignment=Left
apps\1\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\2\desktop=/usr/share/applications/firefox.desktop
apps\size=2
type=quicklaunch

[statusnotifier]
alignment=Right
type=statusnotifier

[sysstat]
alignment=Right
cpu\useFrequency=false
data\source=cpu
data\type=CPU
graph\minimalSize=35
graph\updateInterval=1
graph\useThemeColours=true
grid\lines=0
net\logarithmicScale=true
net\logarithmicScaleSteps=4
net\maximumSpeed=1 MB/s
title\label=
type=sysstat

[taskbar]
alignment=Left
autoRotate=true
buttonHeight=100
buttonStyle=IconText
buttonWidth=200
closeOnMiddleClick=true
cycleOnWheelScroll=true
groupingEnabled=false
iconByClass=false
raiseOnCurrentDesktop=false
showDesktopNum=0
showGroupOnHover=true
showOnlyCurrentScreenTasks=false
showOnlyMinimizedTasks=false
showOnlyOneDesktopTasks=true
type=taskbar

[tray]
alignment=Right
type=tray

[volume]
alignment=Right
audioEngine=PulseAudio
device=0
ignoreMaxVolume=true
type=volume

[worldclock]
alignment=Right
autoRotate=true
customFormat="'<font size=\"2\"><b>'HH:mm:ss'</b><br/><font size=\"1\">'ddd, d.MM.yyyy'</font></font>'"
dateFormatType=custom
dateLongNames=false
datePadDay=false
datePosition=below
dateShowDoW=false
dateShowYear=false
defaultTimeZone=
formatType=custom-timeonly
showDate=true
showTimezone=false
timeAMPM=false
timePadHour=true
timeShowSeconds=true
timeZones\size=0
timezoneFormatType=iana
timezonePosition=below
type=worldclock
useAdvancedManualFormat=true
