alias g='git'
alias l='la'
alias L='less -R'
alias s='ssh'
alias v='~/sbin/nvim'
alias gr='rg'
alias fd='fdfind'
alias sl='ssh-add -l'
alias vd='v -d'
alias cat='batcat'
alias upgrade='sudo apt update && sudo apt upgrade'

alias ,='cd ..'
alias ,,='cd ../..'
alias ,,,='cd ../../..'
alias ,,,,='cd ../../../..'
