# GENERATED from shell/shell.toml by scripts/gen-shell — do not edit

$BLOCKSIZE = 'K'
$CLICOLOR = '1'
$LSCOLORS = 'Gxfxcxdxbxegedabagacad'
$LANGUAGE = 'en_US:en'
$LANG = 'en_US.UTF-8'
$LC_ALL = 'en_US.UTF-8'
$PAGER = 'less -S'
$EDITOR = 'nvim'
$VISUAL = 'nvim'
$BROWSER = 'x-www-browser:local-open'
$NVIM_LOG_FILE = $HOME + '/.cache/nvim/log'
$RIPGREP_CONFIG_PATH = $HOME + '/.config/ripgrep/.ripgreprc'
$SUDO_ASKPASS = $HOME + '/.config/bin/askpass'
$LESS = '-i -x4 -M -R -F -X'
$LESS_TERMCAP_mb = '\x1b[1;31m'
$LESS_TERMCAP_md = '\x1b[1;36m'
$LESS_TERMCAP_me = '\x1b[0m'
$LESS_TERMCAP_so = '\x1b[38;5;016m\x1b[48;5;220m'
$LESS_TERMCAP_se = '\x1b[0m'
$LESS_TERMCAP_us = '\x1b[1;32m'
$LESS_TERMCAP_ue = '\x1b[0m'
$LESS_TERMCAP_zz = '\x1b[0m'

aliases['c'] = ['composerX', '2']
aliases['d'] = ['docker']
aliases['f'] = [$HOME + '/prj/instockcom/ferroctl/ferroctl']
aliases['g'] = ['git']
aliases['k'] = ['kubectl']
aliases['l'] = ['eza', '-la']
aliases['p'] = ['psql_default']
aliases['s'] = ['ssh']
aliases['v'] = ['nvim']
aliases['y'] = ['yazi']
aliases['L'] = ['less', '-R']
aliases['cdd'] = ['cd', $HOME + '/.config']
aliases[','] = ['cd', '..']
aliases[',,'] = ['cd', '../..']
aliases[',,,'] = ['cd', '../../..']
aliases[',,,,'] = ['cd', '../../../..']
aliases[',,,,,'] = ['cd', '../../../../..']
aliases[',,,,,,'] = ['cd', '../../../../../..']
aliases['ls'] = ['eza']
aliases['ll'] = ['eza', '-lAh']
aliases['cat'] = ['bat']
aliases['lt'] = ['eza', '-laT', '-I', '.git|.venv|__pycache__']
aliases['gtree'] = ['eza', '-laT', '--git-ignore', '--git', '-I', '.git|node_modules|vendor', $HOME + '/prj']
aliases['d1'] = ['du', '-hd1']
aliases['grab'] = ['g', 'grab']
aliases['lgrab'] = ['g', 'lgrab']
aliases['clone'] = ['g', 'clone']
aliases['lclone'] = ['g', 'lclone']
aliases['lg'] = ['lazygit']
aliases['gr'] = ['rg', '--no-heading']
aliases['grn'] = ['rg', '--no-line-number', '--no-filename']
aliases['gir'] = ['grep', '-IR']
aliases['girp'] = ['grep', '-IR', '--include=*.php', '--exclude-dir=vendor']
aliases['vim'] = ['nvim']
aliases['ovim'] = ['/usr/bin/vim']
aliases['vimdiff'] = ['v', '-d']
aliases['zconfig'] = ['v', $HOME + '/.config/zsh/.zshrc']
aliases['dc'] = ['docker', 'compose']
aliases['dphp54'] = ['drun', 'php:5.4-cli', 'php']
aliases['dphp81'] = ['drun', 'php:8.1-cli', 'php']
aliases['dphp84'] = ['drun', 'hiqdev/php:8.4-cli-alpine', 'php']
aliases['dco'] = ['dcomposer']
aliases['dp'] = ['docker_psql_default']
aliases['c1'] = ['composerX', '1']
aliases['c2'] = ['composerX', '2']
aliases['phm'] = ['phpuvm']
aliases['ws'] = ['ssh', '-o', 'ConnectionAttempts 300']
aliases['rmsshkey'] = ['ssh-keygen', '-f', $HOME + '/.ssh/known_hosts', '-R']
aliases['nwget'] = ['wget', '--no-check-certificate']
aliases['x509'] = ['openssl', 'x509', '-text', '-noout', '-in']
aliases['ymp3'] = ['yt-dlp', '--add-metadata', '--extract-audio', '--audio-format', 'mp3', '-o', '%(title)s.%(ext)s']
aliases['ypl3'] = ['ymp3', '-w', '--no-post-overwrites', '--download-archive', '.archive.txt', '--ignore-errors']
aliases['ls-tmux'] = ['tmux', 'list-panes', '-aF', '#{session_name}:#{window_index}:#{pane_index}\t#{pane_tty}\t#{pane_pid}\t#{pane_current_command}']
aliases['hr'] = ['herdr', 'machine', 'add']
aliases['upgrade'] = 'sudo apt update && sudo apt upgrade'
aliases['upall'] = '~/.local/bin/mise self-update && ~/.local/bin/mise upgrade && upgrade'
