---
- name: Add syncthing repository key
  apt_key:
    id: "{{ syncthing_apt_key_id }}"
    url: "{{ syncthing_apt_key_url }}"

- name: Add syncthing apt repository
  apt_repository:
    repo: "{{ syncthing_apt_repository }}"

- name: Apt install syncthing
  apt:
    name: syncthing
